name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal Socolin.TestUtils.JsonComparer.Tests.Unit
    - name: Publish JsonComparer
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Socolin.TestUtils.JsonComparer/Socolin.TestUtils.JsonComparer.csproj 
        INCLUDE_SYMBOLS: true
    - name: Publish JsonComparer.NUnitExtensions
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Socolin.TestUtils.JsonComparer.NUnitExtensions/Socolin.TestUtils.JsonComparer.NUnitExtensions.csproj 
        INCLUDE_SYMBOLS: true
    - name: Publish FakeSmtp
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: SoSocolin.TestUtils.FakeSmtp/Socolin.TestUtils.FakeSmtp.csproj 
        INCLUDE_SYMBOLS: true
